### ISSUE TITLE
Planar rectification

### ISSUE THREAD

**Issue by LjIA26** [NHERI-SimCenter/BRAILS#160]
Hello, 

What part of the code does planar rectification?

Thank you.

**Comment by bacetiner** [comment]
Thank you for your question, Lisette. Right now, most of the rectification work is lumped with the FacadeParser module. Please look into this module to see if you are able to find what you had in mind. 

Also, I would like to kindly mention that the [recommended use of GitHub issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue) is to report a bug or make enhancement/other requests. If your query does not quite fall into one of the categories, I would encourage you to use [BRAILS SimCenter forum](https://simcenter-messageboard.designsafe-ci.org/smf/index.php?board=10.0). If you feel your question is too specific for SimCenter forums, please also feel free to contact me at bacetiner@berkeley.edu.

I hope this helps!
