### ISSUE TITLE
Cannot download saved checkpoint of ConstructionTypeClassifier model

### ISSUE THREAD

**Issue by JCBreath** [NHERI-SimCenter/BRAILS#210]
When I initialize the ConstructionTypeClassifier mode, it tried to download the checkpoint from this url: https://zenodo.org/records/7271554/files/trained_model_constype.pth
And it shows that the page is not found

Would you mind sharing the checkpoint?
Or how many images do I need to prepare for each category to train a good model?

**Comment by bacetiner** [comment]
You can download the latest ConstructionTypeClassifier model from [https://zenodo.org/records/13525814/files/constype_classifier_v1.pth](https://zenodo.org/records/13525814/files/constype_classifier_v1.pth). This URL is also built into the ConstructionTypeClassifier default.
