### ISSUE TITLE
'FootprintHandler' object has no attribute 'enabledBaselineInvInputTypes'

### ISSUE THREAD

**Issue by amaccarini** [NHERI-SimCenter/BRAILS#214]
Hi. I just installed the brails package and tried the example workflow:

          `from brails.InventoryGenerator import InventoryGenerator
          
          invGenerator = InventoryGenerator(location='Berkeley, CA',
                                            fpSource='usastr',
                                            baselineInv='nsi',
                                            lengthUnit='m',
                                            outputFile='BaselineInvBerkeleyCA.geojson')
          
          invGenerator.enabled_attributes()
          
          
          invGenerator.generate(attributes='all',
                                GoogleAPIKey='mykey',
                                nbldgs=100,
                                outputFile='BldgInvBerkeleyCA.geojson')
          
          invGenerator.inventory`
          
 I got a GoogleAPIKey and ran the code. However, I get this error:
 `AttributeError: 'FootprintHandler' object has no attribute 'enabledBaselineInvInputTypes'`

**Comment by bacetiner** [comment]
Thank you for reporting this issue. This issue is now addressed.
