### ISSUE TITLE
Incorrect centroid warning.

### ISSUE THREAD

**Issue by claudioperez** [NHERI-SimCenter/BRAILS#26]
The following warning is raised when running `CityBuilder::build`:
```
BRAILS/brails/CityBuilder.py:185: UserWarning: Geometry is in a geographic CRS. Results from 'centroid'
are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.
```
If this is accounted for and the result is known to be correct, the following page can be useful for singling out and silencing the warning:
https://docs.python.org/3/library/warnings.html

**Comment by bacetiner** [comment]
Using Shapely instead of GeoPandas now. Hence, this issue is no longer applicable.
